# Generated by Django 2.2.3 on 2019-07-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190731_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='User',
        ),
    ]
