# Generated by Django 3.0.2 on 2020-03-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_todo_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.CharField(max_length=30)),
                ('todochip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todochip', to='todo.todo')),
            ],
        ),
    ]
