# Generated by Django 3.0.2 on 2020-03-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_todochip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todochip',
            old_name='chip',
            new_name='chips',
        ),
    ]
