# Generated by Django 3.0.2 on 2020-03-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20200301_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todochip',
            name='chips',
            field=models.CharField(default='asdf', max_length=30),
        ),
    ]
