# Generated by Django 3.0.2 on 2020-02-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200207_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='post',
        ),
    ]
