# Generated by Django 3.0.2 on 2020-02-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200207_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posted_by',
            new_name='posted_id',
        ),
    ]
