# Generated by Django 3.0.2 on 2020-02-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200207_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='posts',
            name='posted_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
