# Generated by Django 2.2.5 on 2019-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
