# Generated by Django 2.2.5 on 2019-09-15 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20190915_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
