# Generated by Django 3.0.2 on 2020-02-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
