# Generated by Django 3.0.2 on 2020-03-05 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
