# Generated by Django 2.2.5 on 2020-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_auto_20200124_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
