# Generated by Django 3.0.2 on 2020-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0005_file_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
