# Generated by Django 2.2.5 on 2019-12-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelist',
            old_name='imagelist',
            new_name='src',
        ),
    ]
