# Generated by Django 2.2.5 on 2019-12-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0002_auto_20191231_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='imageslist'),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='thumbnailHeight',
            field=models.IntegerField(default=174),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='thumbnailWidth',
            field=models.IntegerField(default=320),
        ),
    ]
