# Generated by Django 2.2.5 on 2019-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0003_auto_20191231_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='caption',
            field=models.CharField(default='', max_length=50),
        ),
    ]
