# Generated by Django 2.2.5 on 2020-01-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0005_auto_20191231_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
