# Generated by Django 3.0.2 on 2020-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0006_auto_20200130_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='album_id',
            field=models.IntegerField(default=1),
        ),
    ]
