# Generated by Django 3.0.2 on 2020-02-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0007_imagelist_album_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelist',
            name='user',
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagelist', to='imageblock.Images'),
        ),
    ]
