# Generated by Django 3.0.2 on 2020-02-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0009_imagelist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
