# Generated by Django 3.0.2 on 2020-02-27 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblock', '0010_imagelist_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
