# Generated by Django 3.0.2 on 2020-03-15 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200314_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 46, 26, 854733)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='project.ProjectCreate'),
        ),
    ]
