# Generated by Django 3.0.2 on 2020-03-15 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200315_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='task',
            new_name='project_id',
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 47, 50, 917679)),
        ),
    ]
