# Generated by Django 3.0.2 on 2020-03-16 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200315_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 13, 9, 599122)),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(max_length=1000)),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_to', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 13, 9, 603523))),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='project.ProjectCreate')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='project_file')),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_to', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 13, 9, 607061))),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='project.ProjectCreate')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugs', models.TextField(max_length=1000)),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_to', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 13, 9, 601324))),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='project.ProjectCreate')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(max_length=1000)),
                ('requested_by', models.CharField(max_length=50)),
                ('requested_to', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 13, 9, 604873))),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='project.ProjectCreate')),
            ],
        ),
    ]
