# Generated by Django 3.0.2 on 2020-03-16 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200316_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 14, 31, 57, 134664)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 14, 31, 57, 130648)),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 14, 31, 57, 135661)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 14, 31, 57, 132873)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 14, 31, 57, 129647)),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 16, 14, 31, 57, 125530))),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promem', to='project.ProjectCreate')),
            ],
        ),
    ]
