# Generated by Django 3.0.2 on 2020-03-16 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200317_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='requested_to',
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 2, 11, 58, 935126)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 2, 11, 58, 933131)),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 2, 11, 58, 936123)),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 2, 11, 58, 931138)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 2, 11, 58, 934127)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 2, 11, 58, 932134)),
        ),
    ]
