# Generated by Django 3.0.2 on 2020-03-17 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200317_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectactivity',
            old_name='requested_by',
            new_name='image_type',
        ),
        migrations.RenameField(
            model_name='projectactivity',
            old_name='requested_to',
            new_name='name',
        ),
        migrations.AddField(
            model_name='projectbugs',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 132152)),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 132152)),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 132152)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 132152)),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 136152)),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 128129)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 132152)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 7, 16, 132152)),
        ),
    ]
