# Generated by Django 3.0.2 on 2020-03-18 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200318_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectreport',
            old_name='requested_by',
            new_name='posted_by',
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 875018)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 875018)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 875018)),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 877036)),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 866978)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 875018)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 875018)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 36, 38, 875018)),
        ),
    ]
