# Generated by Django 3.0.2 on 2020-03-18 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200318_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 239142)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 238145)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 238145)),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 239142)),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 237159)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 238145)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 237159)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 237159)),
        ),
    ]
