# Generated by Django 3.0.2 on 2020-03-20 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200321_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbugs',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 2, 36, 26, 954817)),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 2, 36, 26, 953819)),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 2, 36, 26, 954817)),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 2, 36, 26, 951826)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 2, 36, 26, 953819)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 2, 36, 26, 952822)),
        ),
    ]
