# Generated by Django 3.0.2 on 2020-06-07 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20200326_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectbugs',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
