# Generated by Django 3.0.2 on 2020-06-07 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20200607_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcreate',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 29, 0, 665657)),
        ),
        migrations.AlterField(
            model_name='projectcreate',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 29, 0, 665635)),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 17, 29, 0, 666194)),
        ),
    ]
