# Generated by Django 3.0.2 on 2020-06-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200607_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcreate',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectcreate',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
