# Generated by Django 3.0.2 on 2020-06-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20200607_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
