# Generated by Django 2.2.5 on 2020-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceadd',
            name='requested_by',
            field=models.IntegerField(default=-1),
        ),
    ]
