# Generated by Django 2.2.5 on 2020-01-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoiceadd_requested_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceAdd',
        ),
    ]
