# Generated by Django 3.0.2 on 2020-03-18 22:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0006_auto_20200107_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProjectJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=50)),
                ('invoice', models.CharField(default='Mem Invoice', max_length=60)),
                ('requested_to', models.CharField(max_length=50)),
                ('project_name_to_join', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 19, 4, 6, 8, 217201))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memadd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
