# Generated by Django 3.0.2 on 2020-03-19 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoiceprojectjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 19, 14, 9, 437920)),
        ),
    ]
