# Generated by Django 3.0.2 on 2020-03-19 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20200319_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceprojectjoin',
            name='requested_to',
        ),
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 19, 17, 36, 595104)),
        ),
    ]
