# Generated by Django 3.0.2 on 2020-03-19 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20200319_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprojectjoin',
            name='message',
            field=models.CharField(default='Mem Invoice', max_length=60),
        ),
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 19, 27, 40, 192865)),
        ),
    ]
