# Generated by Django 3.0.2 on 2020-03-19 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20200319_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprojectjoin',
            name='project_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 1, 45, 40, 233390)),
        ),
    ]
