# Generated by Django 3.0.2 on 2020-03-31 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20200326_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' ', max_length=50)),
                ('status', models.CharField(default=' ', max_length=50)),
                ('order_id', models.CharField(default=' ', max_length=50)),
                ('amount', models.CharField(default=' ', max_length=50)),
                ('bank_name', models.CharField(default=' ', max_length=50)),
                ('transaction_id', models.CharField(default=' ', max_length=50)),
                ('txn_date', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 0, 17, 10, 56705)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 0, 17, 10, 57817)),
        ),
    ]
