# Generated by Django 3.0.2 on 2020-06-10 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0019_auto_20200608_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 21, 40, 317778)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 21, 40, 318339)),
        ),
        migrations.AlterField(
            model_name='subs',
            name='txn_date',
            field=models.CharField(default=datetime.datetime(2020, 6, 10, 17, 21, 40, 318801), max_length=50),
        ),
        migrations.CreateModel(
            name='AllignDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.BooleanField(default=True)),
                ('team', models.BooleanField(default=True)),
                ('diary', models.BooleanField(default=True)),
                ('post', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AllignDashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
