# Generated by Django 3.0.2 on 2020-06-11 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_auto_20200610_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprojectjoin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 27, 29, 538035)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 27, 29, 538721)),
        ),
        migrations.AlterField(
            model_name='subs',
            name='txn_date',
            field=models.CharField(default=datetime.datetime(2020, 6, 11, 15, 27, 29, 539225), max_length=50),
        ),
    ]
