# Generated by Django 3.0.2 on 2020-02-08 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(default='default_team_name', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('designation', models.CharField(default='', max_length=20)),
                ('about_me', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=500)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('skills', models.CharField(default='', max_length=100)),
                ('jobs', models.CharField(default='', max_length=100)),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/default/download_1.jpeg', upload_to='user_image/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
