# Generated by Django 3.0.2 on 2020-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200208_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_image',
            field=models.ImageField(default='/default/default-team-avatar.png', upload_to='team_image'),
        ),
    ]
