# Generated by Django 3.0.2 on 2020-03-21 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200321_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 5, 58, 42, 433247)),
        ),
    ]
